# Generated by Django 4.2.7 on 2025-02-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.JSONField(default=list)),
                ('periods', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('class_duration', models.PositiveIntegerField()),
                ('generated_periods', models.JSONField(default=dict)),
            ],
        ),
    ]
