# Generated by Django 5.1.6 on 2025-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('latest_start_time', models.TimeField()),
                ('min_lessons', models.PositiveIntegerField()),
                ('max_lessons', models.PositiveIntegerField()),
                ('class_groups', models.JSONField()),
            ],
        ),
    ]
