# Generated by Django 5.1.6 on 2025-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_classgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
