# Generated by Django 5.1.6 on 2025-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_scheduleconfig_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='periods',
            field=models.JSONField(default=list),
        ),
    ]
