# Generated by Django 5.1.6 on 2025-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_remove_teacher_user_teacher_email_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='timetable.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unavailable_periods',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
