# Generated by Django 5.1.7 on 2025-04-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_teacher_email_alter_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
    ]
