# Generated by Django 5.1.7 on 2025-04-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_subject_is_practical'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='class_groups',
            field=models.JSONField(default=list),
        ),
    ]
