# Generated by Django 4.2.7 on 2025-07-20 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_timetableentry_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='semester',
            field=models.CharField(default='Fall 2024', max_length=50),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='schedule_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.scheduleconfig'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='semester',
            field=models.CharField(default='Fall 2024', max_length=50),
        ),
    ]
