# Generated by Django 5.2.4 on 2025-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_scheduleconfig_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.CharField(blank=True, help_text='e.g., 21SW, 22SW, 23SW, 24SW', max_length=10, null=True),
        ),
    ]
