# Generated by Django 5.2.4 on 2025-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_subject_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 21SW, 22SW, 23SW, 24SW', max_length=10, unique=True)),
                ('description', models.CharField(help_text='e.g., 8th Semester - Final Year', max_length=100)),
                ('semester_number', models.PositiveIntegerField(help_text='e.g., 8 for 8th semester')),
                ('academic_year', models.CharField(default='2024-2025', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-semester_number'],
            },
        ),
    ]
