# Generated by Django 4.2.7 on 2025-08-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_remove_working_hours_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together=set(),
        ),
    ]
