# Generated by Django 4.2.7 on 2025-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_remove_subject_code_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text='e.g., 21SW, 22SW, 23SW, 24SW, 25SW, etc.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch',
            field=models.CharField(blank=True, help_text='e.g., 21SW, 22SW, 23SW, 24SW, 25SW, etc.', max_length=10, null=True),
        ),
    ]
