# Generated by Django 4.2.7 on 2025-08-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_make_teacher_email_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='max_lessons_per_day',
            new_name='max_classes_per_day',
        ),
    ]
