# Generated by Django 4.2.7 on 2025-08-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_rename_max_lessons_to_max_classes'),
    ]

    operations = [
        migrations.RunSQL(
            # Fix the data: replace 'max_lessons_per_day' string with default value 4
            sql="""
            UPDATE timetable_teacher 
            SET max_classes_per_day = 4 
            WHERE max_classes_per_day = 'max_lessons_per_day';
            """,
            # No reverse operation needed
            reverse_sql=""
        ),
    ]
