# Generated by Django 4.2.7 on 2025-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_department_batch_owner_classroom_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedaccess',
            name='share_batches',
            field=models.BooleanField(default=True, help_text='Share batches data'),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='share_classrooms',
            field=models.BooleanField(default=True, help_text='Share classrooms data'),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='share_constraints',
            field=models.BooleanField(default=True, help_text='Share constraints data'),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='share_subjects',
            field=models.BooleanField(default=True, help_text='Share subjects data'),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='share_teachers',
            field=models.BooleanField(default=True, help_text='Share teachers data'),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='share_timetable',
            field=models.BooleanField(default=True, help_text='Share generated timetable'),
        ),
    ]
