# Generated by Django 4.2.7 on 2025-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_sharedaccess_share_batches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_short_name',
            field=models.CharField(blank=True, help_text='Short name for display (e.g., MATH, CS101)', max_length=10, null=True, unique=True),
        ),
    ]
