# Generated by Django 4.2.7 on 2025-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_add_subject_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='class_advisor',
            field=models.CharField(blank=True, default='', help_text='Name or details of the class advisor for this batch', max_length=255),
        ),
    ]
