# Generated by Django 4.2.7 on 2025-09-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0029_batch_class_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_extra_class',
            field=models.BooleanField(default=False, help_text='Indicates if this is an extra class (with * suffix)'),
        ),
    ]
