# Generated by Django 4.2.7 on 2025-09-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_timetableentry_is_extra_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
